# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/carbonj.service" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/cc-metrics-reporter" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/carbonj.service" # Location of package manifests
    schedule:
      interval: "daily"
